apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.bleadvertiser'
version = '1.0.0'

android {
    namespace 'expo.modules.bleadvertiser'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    lintOptions {
        abortOnError false
    }
}
